{
  "message": "cannot open the connection",
  "traceback": ["file(file, \"rt\")", "read.table(file = file, header = header, sep = sep, quote = quote, \n    dec = dec, fill = fill, comment.char = comment.char, ...)", "read.csv(\"reviews.csv\")", "eval(ei, envir)", "eval(ei, envir)", "withVisible(eval(ei, envir))", "source(file = file, local = envir, echo = echo, encoding = encoding)", "withCallingHandlers({\n    source(file = file, local = envir, echo = echo, encoding = encoding)\n    write_run_property(\"completed\", TRUE)\n}, error = function(e) {\n    write_run_metadata(\"error\", list(message = e$message, traceback = capture_stacktrace(sys.calls())))\n    stop(e)\n})", "force(expr)", "tryCatch({\n    tfruns::training_run(file = deploy$entrypoint, context = deploy$context, \n        config = \"cloudml\", flags = deploy$overlay, encoding = \"UTF-8\", \n        echo = TRUE, view = FALSE, run_dir = run_dir)\n}, error = function(e) {\n    training_error <<- e\n})"]
}
